config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'jokes#index'
  resources :jokes, only: [:index] do
    collection do
      get :fetch_new_record
      get :refresh
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/joke.rb
class Joke < ApplicationRecord
  validates :joke, presence: true

  def self.find_random_joke
    jokes_not_shown = Joke.where(is_shown: false)
    return jokes_not_shown.limit(1).offset(rand(jokes_not_shown.count)).first
  end

  def self.refresh_all
    jokes_shown = Joke.where(is_shown:true)
    jokes_shown.update_all(is_shown: false)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jokes_controller.rb
class JokesController < ApplicationController

  def index
    @jokes = Joke.where(is_shown: true).order('updated_at DESC')
      respond_to do |format|
        format.html
        format.js
      end
  end

  def fetch_new_record
    @random_joke = Joke.find_random_joke
        respond_to do |format|
            if @random_joke.update_attributes(is_shown: true)
              format.html { redirect_to jokes_path, notice: 'fetched new' }
              format.js { @random_joke }
            end
        end
  end

  def refresh
    Joke.refresh_all
      respond_to do |format|
          format.html { redirect_to jokes_path, notice: 'refreshed' }
      end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jokes_helper.rb
module JokesHelper
end

app/views/jokes/_joke.html.erb
<li class="joke-partial" id="joke-id-<%=joke.id%>">
  <p><%= joke.joke %> </p>
</li>

app/views/jokes/fetch_new_record.js.erb
$("#jokes-list").prepend("<%= j (render partial: 'joke', locals: { joke: @random_joke } ) %>");
$("#joke-id-<%= @random_joke.id %>").hide().fadeIn(900)

app/views/jokes/index.html.erb
<div class="jokes_container">

    <div class="manage-buttons">
      <%= button_to "NEW JOKE", fetch_new_record_jokes_path, remote: true, method: :get,  :id => "btn-new-joke" %>

      <%= button_to "REFRESH", refresh_jokes_path, method: :get, :id => "btn-refresh" %>
    </div>


    <div>
        <ul id="jokes-list">
          <% @jokes.each do |joke| -%>
              <%= render partial: "joke", locals: { joke: joke } %>
          <% end -%>
        </ul>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Norrisapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">

  <body>
    <%= yield %>
  </body>
</html>